### ISSUE TITLE
Failing to set installed = off

### ISSUE THREAD

**Issue by lucasdiedrich** [pkp/docker-ojs#18]
Script does not set Installed as **off** or **on** when we bind the config.inc.php file:

![image](https://user-images.githubusercontent.com/817482/81431490-92c78700-9137-11ea-9794-f74c679ab82b.png)

Going to fix this with a PR.

**Comment by marcbria** [comment]
Hi @lucasdiedrich,

Hope you are doing well in this wired new-normality.

Sorry a lot for this long silence. I was talking with pkp fellows in their slack so I just forget about gitHub.

Nothing intentional... it's only you usually have faster feedback in a chat than in a forum, but we decided that conversations need to be public (and in gitHub), so I hope you will join us and I will be able to read you here again.

As you will notice, @AndrewGearhart is just joining the team and comes with nice ideas and energy. :-)
With his help and experience in production environments I feel we will be able to push the project a little bit  further.

Talking with Andrew we arrive to the conclusion that don't make any sense to change installed to Off to modify config.inc.php variables. It's not only that this don't help in keeping ojs safe... is that it can cause more trouble than help, so it's going to be removed.

And as always, I love to hear about your opinion.

Cheers,
m.

**Comment by lucasdiedrich** [comment]
I agree with you guys.
