### ISSUE TITLE
Unexpected issue while trying to use iconv

### ISSUE THREAD

**Issue by jonasraoni** [pkp/docker-ojs#214]
I've tried to execute the following code against the image `pkpofficial/ojs:3_3_0-10`:

```php
echo iconv('ISO-8859-1', 'UTF-8', 'test'); //works
echo iconv('ISO-8859-1', 'UTF-8//IGNORE', 'test'); //fails, but shouldn't
```

And it failed, perhaps this might be helpful to address it: https://github.com/docker-library/php/issues/240#issuecomment-355489551

Origin: https://github.com/pkp/pkp-lib/issues/7765

**Comment by marcbria** [comment]
Thanks a lot for the digging and for pointing the fix.
I will save some time to modify the images next week or so.

**Comment by jonasraoni** [comment]
Good luck! :)
FYI here I'm using a ready PHP image (`FROM php:8.0-apache`), which is working fine.

**Comment by marcbria** [comment]
It needs to be. :-)

Your image is based on Debian and this is good for development (because it includes a lot of stuff) but I feel is better to keep production images over alpine (less is more).

Alpine images are tiny and this means less vulnerability risks and better transfer/management. 

But this is just my opinion and I feel this is the kind of decision we need to be taken collectively, for instance in the RFC issue open in #159.

Thanks for the tip,
m.

**Comment by jonasraoni** [comment]
I agree, that's the way to go, neat and small 🥰
I just left the image that I'm using as a possible reference to solve the problem with `iconv`.

**Comment by marcbria** [comment]
Issue happens because the library was moved in alpine. 
It will be automatically fixed if we move (one day) to debian-slim.

Adding this to the docker file is supposed to work:
```
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.12/community/ gnu-libiconv=1.15-r2
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so

```

Source: https://github.com/docker-library/php/issues/240#issuecomment-762401135

New 3.3.0-11 is built with this but not tested yet.

**Comment by jonasraoni** [comment]
This will fade away, as you're moving to Debian,  so I'm closing this one 😁
