### ISSUE TITLE
base_url never uses https

### ISSUE THREAD

**Issue by frafra** [pkp/docker-ojs#40]
Hi! :)
`SERVERNAME` is used to set up `base_url`, but `http` is always used, which can be incorrect.

**Comment by marcbria** [comment]
Do you mind to extend your explanation and refer the code that you want us to modify?

**Comment by marcbria** [comment]
The only reference I found is ojs-cli-install that is forcing http in the curl call... that is now https.
https://github.com/pkp/docker-ojs/blob/b1be00764ce3c2196529ffcfda26e1cc70e16ea5/templates/common/ojs/usr/local/bin/ojs-cli-install#L9

Base url will use the prefix set by ojs, so it will probably need to be fixed in pkp/ojs repo.
