### ISSUE TITLE
Database encodings latin1 vs utf8

### ISSUE THREAD

**Issue by szitnik** [pkp/docker-ojs#46]
I have seen that there are many errors in the error log like:

`----- PHP Notice:  iconv(): Wrong charset, conversion from 'UTF-8' to 'ISO-8859-1//IGNORE' is not allowed in /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/symfony/polyfill-mbstring/Mbstring.php on line 345`

I believe there is a problem with default database creation at the beginning which defaults to latin1. I solved the problem and propose to change everything to utf-8 by including volumes/config/db.charset.conf into the repo which can look as follows:

```
[client]
default-character-set=utf8mb4
[mysql]
default-character-set=utf8mb4
[mysqld]
collation-server = utf8mb4_unicode_ci
init-connect='SET NAMES utf8mb4'
character-set-server = utf8mb4
```

Source [https://mariadb.com/kb/en/setting-character-sets-and-collations/](https://mariadb.com/kb/en/setting-character-sets-and-collations/).

**Comment by marcbria** [comment]
Thanks @szitnik 

It makes a lot of sense. We will review it soon.

Cheers,
m.

**Comment by marcbria** [comment]
Sorry for the looong silence. This is a side project and I work on this when I get time (that is not very often). :-)

Sometime ago MySQL set utf8mb4 as default so it won't be a problem now.

Anyway, recent conversation with PKP dev team raised a similar issue and the conclusion was "The less we have to internalize MySQL's dev roadmap in our own coding, the better! Let's leave DBMS concerns to the DBA."

So we will apply the same approach here. That is, anyone is free to adapt the project as they need (for example, I have a volume-file for my mysql configuration) but in terms of DB, the project will remain "transparent", with the default configuration. Otherwise we will be appying changes that could collide in some local configurations and in future, we will need to keep them sync between DB engines.

Less is more. ;-)
