### ISSUE TITLE
How do I mount /var/www/html ?

### ISSUE THREAD

**Issue by babyken** [pkp/docker-ojs#98]
Hello, I wanna mount /var/www/html and customize the ojs.
However, everytime I try to mount /var/www/html, the container will only create a public folder in it. And nothing else.
I added the bind in volume in the docker-compose.yml
./volumes/src:/var/www/html

And it works when I didn't try to mount /var/www/html

Anyone has ideas why ?

Thank you.

**Comment by marcbria** [comment]
Hi,

Why do you want to mount /var/www/html? 
You won't be able, but you will probably don't want to do this.

If you are developing plugins, you only need to mount the /plugins folder, if you are working on pkp-lib you will like to map the /lib, if you are working on a theme your theme folder, and so on...

My recommendation is adding the mapping to your docker-compose:

```
    volumes:
      # Plugins folder:
      - ./volumes/plugins:/var/www/html/plugins

```

Cheers,
m.

**Comment by babyken** [comment]
Hi M.

Actually I am facing few issues

1. Implement custom notification
2. Create my own notification template
3. Mute few parts in journal editing so that limit user action
4. Code is amended without source control and I would like to upgrade the ojs

It is why I wanna dig into the source code and see if I could find and modify to fit for purpose.
I am not sure if plugin could fulfil the above needs. Although this is not a right place, it would be great if you could tell me where should I get started.

Thank you very much.

Best,
Ken

**Comment by marcbria** [comment]
From 1 to 3 are problems related with OJS, so please, comment in PKP forum.
About 4, ojs docker containers where though to help in this.

If you keep OJS code untouched (for instance, if you only touch plugins and DB changes) you can easily upgrade just changing your docker-compose file... telling docker to download the new release.

The only precaution that you need to take are the plugins.
If they are in the container, they will be overwritten... and you will be able to upgrade.
If not (ie: mapped as a volume), you need to manually upgrade the plugins before you upgrade.

BTW, I'm also very interested in 3. This is why so long ago I developed "AdminLocker"... a 2.x plugin to lock certain pages to admin users only. If you open a post in pkp forum, mention me (marc) and let's talk them because we will probably find other users interested in this feature.

Cheers,
m.
